
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServicioWebService", targetNamespace = "http://server.soap/", wsdlLocation = "http://192.168.33.65:8080/servicio?wsdl")
public class ServicioWebService
    extends Service
{

    private final static URL SERVICIOWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOWEBSERVICE_EXCEPTION;
    private final static QName SERVICIOWEBSERVICE_QNAME = new QName("http://server.soap/", "ServicioWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.33.65:8080/servicio?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOWEBSERVICE_WSDL_LOCATION = url;
        SERVICIOWEBSERVICE_EXCEPTION = e;
    }

    public ServicioWebService() {
        super(__getWsdlLocation(), SERVICIOWEBSERVICE_QNAME);
    }

    public ServicioWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOWEBSERVICE_QNAME, features);
    }

    public ServicioWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOWEBSERVICE_QNAME);
    }

    public ServicioWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOWEBSERVICE_QNAME, features);
    }

    public ServicioWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioWebInterface
     */
    @WebEndpoint(name = "ServicioWebPort")
    public ServicioWebInterface getServicioWebPort() {
        return super.getPort(new QName("http://server.soap/", "ServicioWebPort"), ServicioWebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioWebInterface
     */
    @WebEndpoint(name = "ServicioWebPort")
    public ServicioWebInterface getServicioWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap/", "ServicioWebPort"), ServicioWebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOWEBSERVICE_EXCEPTION!= null) {
            throw SERVICIOWEBSERVICE_EXCEPTION;
        }
        return SERVICIOWEBSERVICE_WSDL_LOCATION;
    }

}
